-- +migrate Up

CREATE TABLE USER_ROLES (

    USER_ID NUMBER NOT NULL,

    ROLE_ID NUMBER NOT NULL,

    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


    PRIMARY KEY(USER_ID, ROLE_ID),


    CONSTRAINT FK_USER_ROLES_USER
    FOREIGN KEY(USER_ID)
    REFERENCES USERS(USER_ID),


    CONSTRAINT FK_USER_ROLES_ROLE
    FOREIGN KEY(ROLE_ID)
    REFERENCES ROLES(ROLE_ID)

);

