-- +migrate Up

CREATE TABLE ROLE_PERMISSIONS (

    ROLE_ID NUMBER NOT NULL,

    PERMISSION_ID NUMBER NOT NULL,


    PRIMARY KEY(ROLE_ID, PERMISSION_ID),


    CONSTRAINT FK_ROLE_PERMISSION_ROLE
    FOREIGN KEY(ROLE_ID)
    REFERENCES ROLES(ROLE_ID),


    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION
    FOREIGN KEY(PERMISSION_ID)
    REFERENCES PERMISSIONS(PERMISSION_ID)

);


