DELETE FROM ROLE_PERMISSIONS WHERE ROLE_ID IN (SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME IN ('ADMIN','EMPLOYEE'));
DELETE FROM PERMISSIONS WHERE PERMISSION_NAME IN ('USER_READ','USER_CREATE','USER_UPDATE','USER_DELETE','ROLE_READ','ROLE_CREATE','ROLE_UPDATE','ROLE_DELETE','PERMISSION_READ','PERMISSION_CREATE','PERMISSION_UPDATE','PERMISSION_DELETE','ACCESS_REQUEST_READ','ACCESS_REQUEST_CREATE','ACCESS_REQUEST_UPDATE','APPROVAL_READ','APPROVAL_CREATE','AUDIT_READ','AUDIT_CREATE','REPORT_READ','2FA_MANAGE');
DELETE FROM ROLES WHERE ROLE_NAME IN ('ADMIN','EMPLOYEE');
