MERGE INTO ROLES r USING (SELECT 'ADMIN' ROLE_NAME, 'Full system administrator' DESCRIPTION FROM DUAL) x
ON (r.ROLE_NAME = x.ROLE_NAME)
WHEN NOT MATCHED THEN INSERT (ROLE_NAME, DESCRIPTION) VALUES (x.ROLE_NAME, x.DESCRIPTION);
MERGE INTO ROLES r USING (SELECT 'EMPLOYEE' ROLE_NAME, 'Standard application user' DESCRIPTION FROM DUAL) x
ON (r.ROLE_NAME = x.ROLE_NAME)
WHEN NOT MATCHED THEN INSERT (ROLE_NAME, DESCRIPTION) VALUES (x.ROLE_NAME, x.DESCRIPTION);

MERGE INTO PERMISSIONS p USING (SELECT 'USER_READ' NAME, 'Read users' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'USER_CREATE' NAME, 'Create users' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'USER_UPDATE' NAME, 'Update users' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'USER_DELETE' NAME, 'Delete users' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ROLE_READ' NAME, 'Read roles' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ROLE_CREATE' NAME, 'Create roles' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ROLE_UPDATE' NAME, 'Update roles' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ROLE_DELETE' NAME, 'Delete roles' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'PERMISSION_READ' NAME, 'Read permissions' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'PERMISSION_CREATE' NAME, 'Create permissions' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'PERMISSION_UPDATE' NAME, 'Update permissions' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'PERMISSION_DELETE' NAME, 'Delete permissions' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ACCESS_REQUEST_READ' NAME, 'Read access requests' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ACCESS_REQUEST_CREATE' NAME, 'Create access requests' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'ACCESS_REQUEST_UPDATE' NAME, 'Update access requests' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'APPROVAL_READ' NAME, 'Read approvals' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'APPROVAL_CREATE' NAME, 'Create approvals' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'AUDIT_READ' NAME, 'Read audit logs' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'AUDIT_CREATE' NAME, 'Create audit logs' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT 'REPORT_READ' NAME, 'Read reports' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);
MERGE INTO PERMISSIONS p USING (SELECT '2FA_MANAGE' NAME, 'Manage two factor authentication' D FROM DUAL) x ON (p.PERMISSION_NAME=x.NAME) WHEN NOT MATCHED THEN INSERT (PERMISSION_NAME,DESCRIPTION) VALUES(x.NAME,x.D);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID)
SELECT r.ROLE_ID,p.PERMISSION_ID FROM ROLES r CROSS JOIN PERMISSIONS p
WHERE r.ROLE_NAME='ADMIN' AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS rp WHERE rp.ROLE_ID=r.ROLE_ID AND rp.PERMISSION_ID=p.PERMISSION_ID);
INSERT INTO ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID)
SELECT r.ROLE_ID,p.PERMISSION_ID FROM ROLES r JOIN PERMISSIONS p ON p.PERMISSION_NAME IN ('ACCESS_REQUEST_READ','ACCESS_REQUEST_CREATE','2FA_MANAGE')
WHERE r.ROLE_NAME='EMPLOYEE' AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS rp WHERE rp.ROLE_ID=r.ROLE_ID AND rp.PERMISSION_ID=p.PERMISSION_ID);
