package com.ams.modules.passwordreset.service.impl;
import java.security.SecureRandom;import java.time.LocalDateTime;import java.util.Base64;
import com.ams.common.exception.ValidationException;import com.ams.modules.passwordreset.repository.PasswordResetRepository;import com.ams.modules.user.entity.User;import com.ams.modules.user.repository.UserRepository;import com.ams.security.crypto.HashUtils;import com.ams.security.password.BCryptPasswordEncoder;
public class PasswordResetServiceImpl implements com.ams.modules.passwordreset.service.PasswordResetService {
 private final PasswordResetRepository resets;private final UserRepository users;private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();
 public PasswordResetServiceImpl(PasswordResetRepository resets,UserRepository users){this.resets=resets;this.users=users;}
 public String requestReset(String email){if(email==null||email.isBlank())throw new ValidationException("Email is required");User u=users.findByEmail(email.trim()).orElseThrow(()->new ValidationException("No account found for this email"));byte[] b=new byte[32];new SecureRandom().nextBytes(b);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(b);resets.save(u.getUserId(),token,HashUtils.hashData(token),LocalDateTime.now().plusMinutes(15));return token;}
 public void resetPassword(String token,String newPassword){if(token==null||token.isBlank()||newPassword==null||newPassword.length()<8)throw new ValidationException("Valid token and a password of at least 8 characters are required");String hash=HashUtils.hashData(token);Long uid=resets.findValidUserId(hash).orElseThrow(()->new ValidationException("Invalid or expired reset token"));String encoded=encoder.encode(newPassword);User user=users.findById(uid).orElseThrow(()->new ValidationException("User not found"));user.setPasswordHash(encoded);if(!users.update(user))throw new ValidationException("Unable to reset password");if(!resets.markUsed(hash))throw new ValidationException("Reset token could not be consumed");}
}
